### ISSUE TITLE
uuid internals problem

### ISSUE THREAD

**Issue by henryw-erudine** [franks42/cljs-uuid-utils#7]
this fails:
(> (cljs-uuid-utils/make-random-uuid) (cljs-uuid-utils/make-random-uuid))

also, .toString on UUIDs created by this lib does not return what i expect. 

calling .toString on construction would fix these issues... but I see there is another v.similar cljs uuid lib that seems ok, so maybe take this one down from clojars? thanks

**Comment by lbradstreet** [comment]
This works for me for clojurescript-2850. It's possibly a problem with clojurescript not cljs-uuid-utils.

Also, please use the official fork at https://github.com/lbradstreet/cljs-uuid-utils in the future.

Cheers
