### ISSUE TITLE
Non-snapshot release.

### ISSUE THREAD

**Issue by ninjudd** [franks42/cljs-uuid-utils#8]
Hey @franks42, thanks for the library!

 Any chance of getting a non-snapshot release of 1.0.0?

**Comment by lbradstreet** [comment]
Hi @ninjudd. @franks42 has been a bit out of contact and I don't have access to his clojars account / sig. If we don't hear from him soon I may fork the repo and make my own release (I'm able to commit so can point the README to my repo).

**Comment by ninjudd** [comment]
Sounds good! I've also released `[com.ninjudd/cljs-uuid-utils "1.0.0"]` for my own use in the meantime, since random UUIDs before your commit cleaning up `make-random-uuid` appear to be broken.

**Comment by ninjudd** [comment]
Correction, it was @viebel's commit that fixed `make-random-uuid`.

**Comment by chadharrington** [comment]
I'd love to see a non-snapshot release of this, too. In the meantime, I can use ninjudd's.

Thanks.

**Comment by lbradstreet** [comment]
Alright. I'm going to fork it and point the README to the fork. It'll have to be released under new coordinates unfortunately.

**Comment by franks42** [comment]
Sorry for my lack of support - should check my github account more often...
Not sure if my current work allows me to do a much better job in the future.
I do not mind anyone taking-over the main support by forking it or by becoming co-owners - what is the easiest/best way to go about it?

**Comment by lbradstreet** [comment]
Hi Frank,

The main hold up at the moment is that even though I have access to the repo I don't have any way to deploy to clojars with the same coordinates. You need to give me access to your clojars account or find some way to transfer that coordinate to my control.

I'm not sure how to do this though. 

Otherwise I was going to fork and point the old repo to the new repo and deploy to new coordinates. 

Cheers

Lucas

**Comment by franks42** [comment]
Hi Lucas - Why don't we do that - you'll fork this repo and take over the maintenance completely - we'll make sure to change the README here to explain that the effort here is deprecated and point people at the new coordinates - thanks for your help!!! - Regards, Frank.

**Comment by lbradstreet** [comment]
Forked at https://github.com/lbradstreet/cljs-uuid-utils with new release. Thanks!
