### ISSUE TITLE
Switch from single segment namespace

### ISSUE THREAD

**Issue by ninjudd** [franks42/cljs-uuid-utils#9]
I get the following warning with the latest Clojurescript `[org.clojure/clojurescript "0.0-2913"]`:

```
WARNING: cljs-uuid-utils is a single segment namespace at line 9 cljs_uuid_utils.cljs
```

**Comment by lbradstreet** [comment]
Fixed in fork https://github.com/lbradstreet/cljs-uuid-utils

Thanks
